import { createAdminClient } from '@/lib/supabase/admin'
import { SEED_CLIENT_EMAILS } from './seed-clients'
import type { SeedResult } from './types'
import type { Database } from '@/types/database'

type ItemInsert = Database['public']['Tables']['items']['Insert']
type ItemStatus = Database['public']['Enums']['item_status']
type ItemCategory = Database['public']['Enums']['item_category']
type ItemLocation = Database['public']['Enums']['item_location']

interface SeedItem extends Omit<ItemInsert, 'client_id' | 'is_seed_data'> {
  client_email: string
}

// ── Item name → deterministic UUID (used by orders, outfits, conditions) ─────
// Pattern: first 8 chars = item index hex, rest fixed
// Item IDs exported so orders/outfits can reference by name lookup at runtime.
// We do NOT hardcode IDs here — items are looked up by (client_id, name).

const SEED_ITEMS: SeedItem[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // Client 1: Margaret Hartwell — target 48 items
  // Distribution: ~29 WI stored, ~12 AZ stored/with-client, ~4 at-provider, ~3 in-transit
  // ══════════════════════════════════════════════════════════════════════════

  // ── Formalwear / Eveningwear ──────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Midnight Navy Tuxedo Jacket',
    category: 'suiting' as ItemCategory,
    brand: 'Brioni',
    color: 'Navy',
    size: '42R',
    material: 'Super 150s Wool',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 8500,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['tuxedo', 'formalwear', 'brioni'],
    description: 'Bespoke single-breasted tuxedo jacket with peak lapels and silk facing. Purchased 2021.',
    care_instructions: 'Dry clean only. Press with low heat through pressing cloth.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Black Tuxedo Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Brioni',
    color: 'Black',
    size: '34x32',
    material: 'Super 150s Wool with Silk Braid',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 1800,
    status: 'cleaning_complete' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['tuxedo', 'trousers', 'brioni'],
    description: 'Matching tuxedo trousers to the navy jacket. Silk braid stripe on outseam.',
    care_instructions: 'Dry clean only. Hang immediately after cleaning.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Ivory Silk Evening Gown',
    category: 'eveningwear' as ItemCategory,
    brand: 'Carolina Herrera',
    color: 'Ivory',
    size: '6',
    material: 'Silk Charmeuse',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 5800,
    status: 'in_cleaning' as ItemStatus,
    location_status: 'at_provider_az' as ItemLocation,
    location_label: 'RAVE FabriCARE — Order #AZ-4421',
    tags: ['gown', 'eveningwear', 'silk', 'carolina-herrera'],
    description: 'Floor-length ivory silk charmeuse gown with a draped cowl back. Worn at the Desert Philanthropists Gala.',
    care_instructions: 'Professional wet clean only. No solvents on silk charmeuse.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Blush Embellished Cocktail Dress',
    category: 'eveningwear' as ItemCategory,
    brand: 'Monique Lhuillier',
    color: 'Blush',
    size: '6',
    material: 'Beaded Chiffon',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 4200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['cocktail', 'beaded', 'monique-lhuillier', 'eveningwear'],
    description: 'Strapless A-line cocktail dress with allover beading in blush. Fully lined with boning in bodice.',
    care_instructions: 'Dry clean only. Store flat or on padded hanger.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Champagne Sequin Column Gown',
    category: 'eveningwear' as ItemCategory,
    brand: 'Jenny Packham',
    color: 'Champagne',
    size: '6',
    material: 'Sequined Mesh over Silk',
    season: 'fall/winter',
    purchase_year: 2020,
    purchase_price: 3600,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['gown', 'sequin', 'jenny-packham', 'eveningwear'],
    description: 'Floor-length sequined column gown in champagne. Cap sleeves. Invisible zip at back.',
    care_instructions: 'Dry clean only. Store in breathable garment bag, do not compress sequins.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Navy Crepe Wrap Dress',
    category: 'dresses' as ItemCategory,
    brand: 'Roland Mouret',
    color: 'Navy',
    size: '6',
    material: 'Crepe',
    season: 'all',
    purchase_year: 2023,
    purchase_price: 2200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['wrap-dress', 'roland-mouret', 'crepe'],
    description: 'Roland Mouret Poppy wrap dress in structured crepe. Three-quarter sleeves.',
    care_instructions: 'Dry clean only.',
  },

  // ── Suiting ───────────────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Heather Grey Flannel Suit',
    category: 'suiting' as ItemCategory,
    brand: 'Kiton',
    color: 'Heather Grey',
    size: '42R',
    material: 'Super 180s Flannel Wool',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 7200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['suit', 'flannel', 'kiton'],
    description: 'Two-button slim-fit suit in Napoli tailoring. Patch pockets. Two pairs of trousers included.',
    care_instructions: 'Dry clean only. Steam lightly to remove creases.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Ivory Bouclé Skirt Suit',
    category: 'suiting' as ItemCategory,
    brand: 'Chanel',
    color: 'Ivory',
    size: '40',
    material: 'Wool Bouclé',
    season: 'all',
    purchase_year: 2019,
    purchase_price: 9800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['suit', 'chanel', 'boucle', 'vintage'],
    description: 'Classic Chanel ivory bouclé skirt suit with gilt buttons. Silk-lined. Purchased at Chanel Boutique Chicago.',
    care_instructions: 'Dry clean only. Never machine wash bouclé.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Black Cashmere Blazer',
    category: 'suiting' as ItemCategory,
    brand: 'Brunello Cucinelli',
    color: 'Black',
    size: 'S',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2023,
    purchase_price: 3400,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['blazer', 'cashmere', 'brunello-cucinelli'],
    description: 'Relaxed single-button blazer in pure cashmere. Monili cuff trim.',
    care_instructions: 'Dry clean only.',
  },

  // ── Outerwear ─────────────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Sable Brown Cashmere Overcoat',
    category: 'outerwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Sable Brown',
    size: '6',
    material: 'Baby Cashmere',
    season: 'fall/winter',
    purchase_year: 2020,
    purchase_price: 6500,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['cashmere', 'overcoat', 'loro-piana'],
    description: 'Double-breasted cashmere overcoat with tortoise shell buttons. Storm cuffs.',
    care_instructions: 'Dry clean only. Store in breathable garment bag with cedar.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Navy Cashmere Car Coat',
    category: 'outerwear' as ItemCategory,
    brand: 'Max Mara',
    color: 'Navy',
    size: '6',
    material: 'Cashmere Blend',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 2800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['car-coat', 'cashmere', 'max-mara'],
    description: 'Max Mara 101801 Manuela car coat in navy cashmere blend. The iconic silhouette.',
    care_instructions: 'Dry clean only. Store hanging in breathable cover.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Ivory Shearling Vest',
    category: 'outerwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Ivory',
    size: 'S',
    material: 'Merino Shearling',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 4200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shearling', 'vest', 'loro-piana'],
    description: 'Reversible shearling-to-suede gilet in winter white. Concealed snap closure.',
    care_instructions: 'Professional shearling cleaning only. Never machine wash.',
  },

  // ── Knitwear ──────────────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Ivory Cashmere V-neck Sweater',
    category: 'knitwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Ivory',
    size: 'S',
    material: 'Baby Cashmere',
    season: 'fall/winter',
    purchase_year: 2023,
    purchase_price: 1800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['cashmere', 'knitwear', 'loro-piana'],
    description: 'Superfine baby cashmere V-neck in winter ivory. Classic fit.',
    care_instructions: 'Hand wash cold or dry clean. Lay flat to dry. Store folded with cedar.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Camel Cashmere Turtleneck',
    category: 'knitwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Camel',
    size: 'S',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 1600,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['cashmere', 'turtleneck', 'loro-piana'],
    description: 'Slim-fit cashmere turtleneck in warm camel. Ribbed cuffs and hem.',
    care_instructions: 'Hand wash cold. Lay flat to dry.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Navy Cashmere Cardigan',
    category: 'knitwear' as ItemCategory,
    brand: 'Brunello Cucinelli',
    color: 'Navy',
    size: 'S',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 2200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['cashmere', 'cardigan', 'brunello-cucinelli'],
    description: 'Oversized cashmere cardigan with pockets and tortoise buttons.',
    care_instructions: 'Dry clean only.',
  },

  // ── Shirts & Blouses ──────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'White Silk Charmeuse Blouse',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Equipment',
    color: 'White',
    size: 'S',
    material: 'Silk Charmeuse',
    season: 'all',
    purchase_year: 2023,
    purchase_price: 320,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['blouse', 'silk', 'equipment'],
    description: 'Equipment Femme relaxed silk charmeuse blouse. Notch collar.',
    care_instructions: 'Hand wash cold or dry clean. Lay flat.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Striped Cotton Oxford Shirt',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Thomas Mason',
    color: 'Blue Stripe',
    size: 'S',
    material: 'Egyptian Cotton Oxford',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 280,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['shirt', 'oxford', 'stripe', 'cotton'],
    description: 'Thomas Mason classic Oxford stripe in blue on white. Button-down collar.',
    care_instructions: 'Machine wash cold. Light starch. Press.',
  },

  // ── Trousers & Skirts ─────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Camel Wide-Leg Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'The Row',
    color: 'Camel',
    size: '4',
    material: 'Wool Crepe',
    season: 'fall/winter',
    purchase_year: 2023,
    purchase_price: 1400,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['trousers', 'the-row', 'wide-leg', 'wool'],
    description: 'High-waisted wide-leg trousers in wool crepe. Flat front. The Row SS23.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Navy Silk Midi Skirt',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Valentino',
    color: 'Navy',
    size: '6',
    material: 'Silk Satin',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 1800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['skirt', 'silk', 'valentino', 'midi'],
    description: 'Valentino midi skirt in navy silk satin with pleated front. Side zip.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Black Cashmere Straight-Leg Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Black',
    size: '6',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 1600,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['trousers', 'cashmere', 'loro-piana'],
    description: 'Loro Piana straight-leg trousers in double-faced cashmere. Clean minimal cut.',
    care_instructions: 'Dry clean only.',
  },

  // ── Handbags ──────────────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Gold Hermes Kelly 32',
    category: 'handbags' as ItemCategory,
    brand: 'Hermès',
    color: 'Gold',
    size: '32',
    material: 'Togo Leather',
    season: 'all',
    purchase_year: 2018,
    purchase_price: 12000,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['hermes', 'kelly', 'handbag', 'investment'],
    description: 'Gold Togo leather Kelly 32 with palladium hardware. Original box and clochette included.',
    care_instructions: 'Store stuffed with tissue. Condition with Hermès leather care annually.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Black Chanel Classic Flap Medium',
    category: 'handbags' as ItemCategory,
    brand: 'Chanel',
    color: 'Black',
    material: 'Lambskin Leather',
    season: 'all',
    purchase_year: 2020,
    purchase_price: 8200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['chanel', 'classic-flap', 'handbag', 'investment'],
    description: 'Chanel Classic Flap in black lambskin with gold hardware. Medium size. Authenticity card included.',
    care_instructions: 'Store stuffed in dust bag. Condition annually. Keep away from moisture.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Tan Hermès Birkin 30',
    category: 'handbags' as ItemCategory,
    brand: 'Hermès',
    color: 'Tan',
    size: '30',
    material: 'Epsom Leather',
    season: 'all',
    purchase_year: 2015,
    purchase_price: 14000,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['hermes', 'birkin', 'handbag', 'investment'],
    description: 'Hermès Birkin 30 in Epsom leather, gold Clémence hardware. With clochette, padlock, keys, and original orange box.',
    care_instructions: 'Condition annually. Store away from direct light.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Ivory Minaudière Evening Clutch',
    category: 'handbags' as ItemCategory,
    brand: 'Judith Leiber',
    color: 'Ivory',
    material: 'Crystal-Encrusted Satin',
    season: 'all',
    purchase_year: 2019,
    purchase_price: 3800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['clutch', 'judith-leiber', 'eveningwear', 'crystal'],
    description: 'Judith Leiber Couture floral crystal minaudière in ivory. 18k gold-plated hardware.',
    care_instructions: 'Store in dust bag. Do not expose to moisture.',
  },

  // ── Footwear ──────────────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Black Patent Leather Oxfords',
    category: 'footwear' as ItemCategory,
    brand: "Church's",
    color: 'Black',
    size: '8',
    material: 'Patent Leather',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 950,
    status: 'received' as ItemStatus,
    location_status: 'at_provider_az' as ItemLocation,
    location_label: 'European Couture Cleaners — Shoe Restoration',
    tags: ['shoes', 'oxfords', 'formalwear', 'churches'],
    description: "Church's Consul patent leather cap-toe oxfords. Heel restoration in progress.",
    care_instructions: 'Polish with patent leather cleaner only. Store with shoe trees.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Nude Suede Slingback Pumps',
    category: 'footwear' as ItemCategory,
    brand: 'Manolo Blahnik',
    color: 'Nude',
    size: '8',
    material: 'Suede',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 725,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['shoes', 'manolo-blahnik', 'pumps', 'suede'],
    description: 'Manolo Blahnik BB 105mm slingback pumps in nude suede.',
    care_instructions: 'Store in original box with shoe bags. Brush suede gently.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Black Satin Evening Pumps',
    category: 'footwear' as ItemCategory,
    brand: 'Jimmy Choo',
    color: 'Black',
    size: '8',
    material: 'Satin',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 650,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['shoes', 'jimmy-choo', 'pumps', 'satin', 'formalwear'],
    description: 'Jimmy Choo Romy 100mm satin pumps. Formal wear staple.',
    care_instructions: 'Store in dust bag inside original box. Spot clean only.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Tan Leather Walking Loafers',
    category: 'footwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Tan',
    size: '38',
    material: 'Calfskin',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 1100,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['shoes', 'loro-piana', 'loafers', 'casual'],
    description: 'Loro Piana Summer Walk loafers in tan calfskin. Current season.',
    care_instructions: 'Condition monthly. Store with cedar shoe trees.',
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Diamond Tennis Bracelet',
    category: 'accessories' as ItemCategory,
    brand: 'Cartier',
    color: 'Silver/White',
    material: 'Platinum, Round Brilliant Diamonds',
    season: 'all',
    purchase_year: 2017,
    purchase_price: 15000,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['jewelry', 'cartier', 'diamonds', 'accessories'],
    description: 'Cartier platinum tennis bracelet, approximately 5ct total diamond weight. Stored in original box.',
    care_instructions: 'Store in original presentation box. Professional cleaning annually.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Ivory Cashmere Travel Shawl',
    category: 'accessories' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Ivory',
    material: 'Baby Cashmere',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 1800,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['shawl', 'cashmere', 'loro-piana', 'accessories'],
    description: 'Loro Piana baby cashmere travel shawl in ivory. 200cm x 90cm.',
    care_instructions: 'Hand wash cold or dry clean.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Navy Silk Twill Scarf',
    category: 'accessories' as ItemCategory,
    brand: 'Hermès',
    color: 'Navy',
    material: 'Silk Twill',
    season: 'all',
    purchase_year: 2020,
    purchase_price: 450,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['scarf', 'hermes', 'silk', 'accessories'],
    description: "Hermès Les Cavaliers d'Or 90cm silk twill scarf in navy and gold.",
    care_instructions: 'Hand wash cold in gentle soap. Press with silk setting through pressing cloth.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Pearl Strand Necklace',
    category: 'accessories' as ItemCategory,
    brand: 'Mikimoto',
    color: 'Ivory',
    material: 'Akoya Cultured Pearls, 18k White Gold',
    season: 'all',
    purchase_year: 2016,
    purchase_price: 8500,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['jewelry', 'mikimoto', 'pearls', 'necklace'],
    description: 'Mikimoto 7.5-8mm Akoya pearl strand, 18-inch, 18k white gold clasp. Original certificate.',
    care_instructions: 'Store in pouch. Clean with damp soft cloth. Restring every 3 years.',
  },

  // ── Richard Hartwell (Margaret's husband) items ────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: "Richard's Charcoal Brioni Suit",
    category: 'suiting' as ItemCategory,
    brand: 'Brioni',
    color: 'Charcoal',
    size: '44R',
    material: 'Super 150s Wool',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 9500,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['suit', 'brioni', 'charcoal', 'richard'],
    description: "Richard Hartwell's bespoke Brioni charcoal suit. Two-button. Surgeon cuffs.",
    care_instructions: 'Dry clean only. Hang on shaped hanger.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: "Richard's Navy Blazer",
    category: 'suiting' as ItemCategory,
    brand: 'Canali',
    color: 'Navy',
    size: '44R',
    material: 'Wool',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 1800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['blazer', 'canali', 'navy', 'richard'],
    description: "Richard Hartwell's Canali navy sport blazer with brass buttons.",
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: "Richard's Black Tuxedo Set",
    category: 'suiting' as ItemCategory,
    brand: 'Hugo Boss',
    color: 'Black',
    size: '44R',
    material: 'Super 100s Wool',
    season: 'all',
    purchase_year: 2020,
    purchase_price: 1500,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['tuxedo', 'boss', 'black', 'richard'],
    description: "Richard Hartwell's Hugo Boss black tuxedo jacket and matching trousers. Satin lapels.",
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: "Richard's Tan Cashmere Topcoat",
    category: 'outerwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Tan',
    size: '44R',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2019,
    purchase_price: 5200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['overcoat', 'cashmere', 'loro-piana', 'richard'],
    description: "Richard Hartwell's Loro Piana tan cashmere single-breasted topcoat.",
    care_instructions: 'Dry clean only. Store with cedar. Breathable garment bag.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: "Richard's White Tuxedo Dress Shirts (3)",
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Turnbull & Asser',
    color: 'White',
    size: '17/35',
    material: 'Sea Island Cotton',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 1800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['shirts', 'tuxedo', 'turnbull-asser', 'richard'],
    description: "Richard Hartwell's Turnbull & Asser marcella front tuxedo shirts. Set of 3.",
    care_instructions: 'Launder with starch. Professional pressing preferred.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: "Richard's Allen Edmonds Dress Shoes",
    category: 'footwear' as ItemCategory,
    brand: 'Allen Edmonds',
    color: 'Black',
    size: '11D',
    material: 'Calfskin',
    season: 'all',
    purchase_year: 2020,
    purchase_price: 450,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shoes', 'allen-edmonds', 'black', 'richard'],
    description: "Richard Hartwell's Allen Edmonds Park Avenue black cap-toe oxfords. Cedar shoe trees included.",
    care_instructions: 'Polish monthly. Store with cedar shoe trees.',
  },

  // ── Swimwear / Resort ─────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Navy Swimsuit Cover-Up Kaftan',
    category: 'swimwear' as ItemCategory,
    brand: 'Missoni',
    color: 'Navy Multi',
    size: 'S',
    material: 'Silk Blend Knit',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 680,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['swimwear', 'kaftan', 'missoni', 'resort'],
    description: 'Missoni signature zigzag knit kaftan in navy/gold. Current season resort.',
    care_instructions: 'Hand wash cold. Dry flat.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'White Linen Beach Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Vilebrequin',
    color: 'White',
    size: '6',
    material: 'Linen',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 280,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['linen', 'trousers', 'resort', 'vilebrequin'],
    description: 'Vilebrequin Pacha wide-leg linen trousers in white.',
    care_instructions: 'Machine wash cold. Line dry.',
  },

  // ── In Transit ────────────────────────────────────────────────────────────
  {
    client_email: 'client1@test.llv.com',
    name: 'Blush Silk Wrap Blouse',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Diane von Furstenberg',
    color: 'Blush',
    size: 'S',
    material: 'Silk Jersey',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 498,
    status: 'delivery_scheduled' as ItemStatus,
    location_status: 'in_transit' as ItemLocation,
    tags: ['blouse', 'silk', 'dvf', 'wrap'],
    description: 'DVF silk jersey wrap blouse in blush. Currently in transit from WI to AZ storage.',
    care_instructions: 'Hand wash cold or machine wash delicate.',
  },
  {
    client_email: 'client1@test.llv.com',
    name: 'Grey Flannel Trouser (Margaret)',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Grey',
    size: '6',
    material: 'Flannel Wool',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 1200,
    status: 'delivery_scheduled' as ItemStatus,
    location_status: 'in_transit' as ItemLocation,
    tags: ['trousers', 'flannel', 'loro-piana'],
    description: 'Loro Piana grey flannel flat-front trousers. In transit.',
    care_instructions: 'Dry clean only.',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Client 2: Catherine Beaumont — target 38 items
  // Distribution: ~22 WI stored, ~10 AZ stored/with-client, ~4 at-provider, ~2 in-transit
  // ══════════════════════════════════════════════════════════════════════════

  // ── Eveningwear ───────────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Sapphire Silk Cocktail Dress',
    category: 'dresses' as ItemCategory,
    brand: 'Oscar de la Renta',
    color: 'Sapphire Blue',
    size: '4',
    material: 'Silk Mikado',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 4800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['cocktail', 'oscar-de-la-renta', 'silk', 'eveningwear'],
    description: 'Structured cocktail-length dress in sapphire silk mikado. Sculptural bow at hip. Fully boned bodice.',
    care_instructions: 'Dry clean only. Store hanging in breathable cover.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Blush Valentino Couture Gown',
    category: 'eveningwear' as ItemCategory,
    brand: 'Valentino',
    color: 'Blush',
    size: '4',
    material: 'Silk Tulle over Crepe',
    season: 'spring/summer',
    purchase_year: 2021,
    purchase_price: 8500,
    status: 'in_cleaning' as ItemStatus,
    location_status: 'at_provider_az' as ItemLocation,
    location_label: 'European Couture Cleaners — repair in progress',
    tags: ['gown', 'valentino', 'couture', 'eveningwear'],
    description: 'Valentino SS2021 silk tulle ballgown with embroidered hem. Pull on left sleeve under repair.',
    care_instructions: 'Hand clean only. No solvents on tulle.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Emerald Satin Column Gown',
    category: 'eveningwear' as ItemCategory,
    brand: 'Halston',
    color: 'Emerald',
    size: '4',
    material: 'Charmeuse Satin',
    season: 'fall/winter',
    purchase_year: 2020,
    purchase_price: 2200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['gown', 'halston', 'satin', 'eveningwear'],
    description: 'Halston halter column gown in emerald charmeuse. Bias-cut. Simple elegance.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Black Velvet Evening Gown',
    category: 'eveningwear' as ItemCategory,
    brand: 'Ralph Lauren Collection',
    color: 'Black',
    size: '4',
    material: 'Silk Velvet',
    season: 'fall/winter',
    purchase_year: 2019,
    purchase_price: 3800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['gown', 'ralph-lauren', 'velvet', 'eveningwear'],
    description: 'Ralph Lauren Collection off-the-shoulder silk velvet gown. Built-in boning. Full skirt.',
    care_instructions: 'Dry clean only. Store on padded hanger. Never crush velvet.',
  },

  // ── Suiting ───────────────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'White Structured Linen Blazer',
    category: 'suiting' as ItemCategory,
    brand: 'Max Mara',
    color: 'Optical White',
    size: '6',
    material: 'Linen',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 890,
    status: 'stored' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['blazer', 'linen', 'max-mara', 'summer'],
    description: 'Classic Max Mara double-breasted linen blazer. Gold-tone buttons. Partially lined.',
    care_instructions: 'Dry clean preferred. Hand wash cold if needed. Press while slightly damp.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Black Chanel Boucle Jacket',
    category: 'suiting' as ItemCategory,
    brand: 'Chanel',
    color: 'Black',
    size: '40',
    material: 'Wool Bouclé',
    season: 'fall/winter',
    purchase_year: 2018,
    purchase_price: 7200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['jacket', 'chanel', 'boucle', 'suiting'],
    description: 'Chanel black bouclé jacket with signature chain hem. CC buttons. Paris-Bombay collection.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Navy Silk Blazer',
    category: 'suiting' as ItemCategory,
    brand: 'Akris',
    color: 'Navy',
    size: '6',
    material: 'Silk Taffeta',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 2400,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['blazer', 'silk', 'akris', 'navy'],
    description: 'Akris single-button tuxedo blazer in navy silk taffeta.',
    care_instructions: 'Dry clean only.',
  },

  // ── Outerwear ─────────────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Camel Cashmere Wrap Coat',
    category: 'outerwear' as ItemCategory,
    brand: 'Brunello Cucinelli',
    color: 'Warm Camel',
    size: '6',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 5400,
    status: 'in_cleaning' as ItemStatus,
    location_status: 'at_provider_az' as ItemLocation,
    location_label: 'European Couture Cleaners — Order #SC-0872',
    tags: ['cashmere', 'coat', 'brunello-cucinelli', 'wrap'],
    description: 'Oversized wrap coat in warm camel cashmere with self-tie belt. Monili trim at cuffs.',
    care_instructions: 'Dry clean only. Never machine wash. Brush gently between cleans.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Black Wool Cocoon Coat',
    category: 'outerwear' as ItemCategory,
    brand: 'Akris',
    color: 'Black',
    size: '6',
    material: 'Double-Faced Wool',
    season: 'fall/winter',
    purchase_year: 2020,
    purchase_price: 4200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['coat', 'wool', 'akris', 'cocoon'],
    description: 'Akris cocoon coat in double-faced black wool. No lining needed. Invisible zip.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Ivory Cashmere Full-Length Coat',
    category: 'outerwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Ivory',
    size: '6',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 6800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['coat', 'cashmere', 'loro-piana', 'full-length'],
    description: 'Loro Piana full-length coat in ivory cashmere. Double-breasted with cascade lapels.',
    care_instructions: 'Dry clean only. Cedar blocks in storage bag.',
  },

  // ── Knitwear ──────────────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Ivory Fine Cashmere Turtleneck',
    category: 'knitwear' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Ivory',
    size: 'XS',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 1400,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['cashmere', 'turtleneck', 'loro-piana'],
    description: 'Fine cashmere polo neck in ivory. Ribbed cuffs and hem.',
    care_instructions: 'Hand wash cold or dry clean.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Navy Merino Slim Pullover',
    category: 'knitwear' as ItemCategory,
    brand: 'Eric Bompard',
    color: 'Navy',
    size: 'XS',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 380,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['cashmere', 'pullover', 'eric-bompard'],
    description: 'Eric Bompard slim-fit v-neck cashmere pullover in navy.',
    care_instructions: 'Hand wash cold. Dry flat.',
  },

  // ── Shirts & Blouses ──────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Floral Silk Print Blouse',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Valentino',
    color: 'Multicolor',
    size: '6',
    material: 'Silk Twill',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 1800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['silk', 'blouse', 'valentino', 'print'],
    description: 'Valentino SS2023 floral print silk twill blouse. Pussybow collar. Never worn.',
    care_instructions: 'Hand wash only in cold water. No solvents. Dry flat.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Ivory Silk Charmeuse Blouse',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'The Row',
    color: 'Ivory',
    size: '4',
    material: 'Silk Charmeuse',
    season: 'all',
    purchase_year: 2023,
    purchase_price: 890,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['blouse', 'silk', 'the-row'],
    description: 'The Row Sibel blouse in ivory silk charmeuse. Draped front.',
    care_instructions: 'Dry clean only.',
  },

  // ── Trousers & Skirts ─────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Black Wide-Leg Crepe Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'The Row',
    color: 'Black',
    size: '6',
    material: 'Silk Crepe',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 1200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['trousers', 'the-row', 'silk', 'wide-leg'],
    description: 'The Row high-waisted wide-leg trousers in silk crepe. Clean minimal aesthetic.',
    care_instructions: 'Dry clean only. Hang or fold on creases.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Ivory Silk Pleated Midi Skirt',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Celine',
    color: 'Ivory',
    size: '4',
    material: 'Silk Satin',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 1600,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['skirt', 'silk', 'celine', 'pleated'],
    description: 'Celine pleated midi skirt in ivory silk satin. Elasticated waist.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Camel Cashmere Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Brunello Cucinelli',
    color: 'Camel',
    size: '6',
    material: 'Cashmere',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 1800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['trousers', 'cashmere', 'brunello-cucinelli'],
    description: 'Brunello Cucinelli straight-leg trousers in pure cashmere.',
    care_instructions: 'Dry clean only.',
  },

  // ── Handbags ──────────────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Cognac Python Evening Clutch',
    category: 'handbags' as ItemCategory,
    brand: 'Saint Laurent',
    color: 'Cognac',
    material: 'Python Leather',
    season: 'all',
    purchase_year: 2020,
    purchase_price: 2800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['clutch', 'saint-laurent', 'python', 'eveningwear'],
    description: 'YSL envelope clutch in genuine python. Gold-tone clasp. Original dust bag included.',
    care_instructions: 'Store in dust bag. Avoid moisture and direct sunlight. No conditioning.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Black Dior Lady Bag',
    category: 'handbags' as ItemCategory,
    brand: 'Dior',
    color: 'Black',
    material: 'Cannage Lambskin',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 5200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['handbag', 'dior', 'lady-dior', 'investment'],
    description: 'Lady Dior medium bag in black lambskin with Cannage quilting. Gold-tone hardware. Certificate included.',
    care_instructions: 'Store stuffed in dust bag. No direct light.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Camel Hermès Garden Party Tote',
    category: 'handbags' as ItemCategory,
    brand: 'Hermès',
    color: 'Camel',
    material: 'Negonda Leather',
    season: 'spring/summer',
    purchase_year: 2019,
    purchase_price: 4100,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['tote', 'hermes', 'garden-party'],
    description: "Hermès Garden Party 36 in camel Negonda leather. Current season's everyday bag.",
    care_instructions: 'Condition monthly. Store stuffed.',
  },

  // ── Footwear ──────────────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Gold Drop Earrings',
    category: 'accessories' as ItemCategory,
    brand: 'David Yurman',
    color: 'Gold',
    material: '18k Gold, Citrine',
    season: 'all',
    purchase_year: 2020,
    purchase_price: 3200,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['jewelry', 'david-yurman', 'earrings'],
    description: 'David Yurman Châtelaine drop earrings in 18k yellow gold with citrine. Returned to client for current season.',
    care_instructions: 'Store in jewelry pouch. Clean with soft cloth only.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Blush Satin Strappy Mules',
    category: 'footwear' as ItemCategory,
    brand: 'Jimmy Choo',
    color: 'Blush',
    size: '8',
    material: 'Satin',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 650,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['shoes', 'jimmy-choo', 'satin', 'mules'],
    description: 'Jimmy Choo Daria 60mm satin mules in blush. Barely worn. In original box.',
    care_instructions: 'Store in shoe bag inside original box. Spot clean only.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Black Satin Ankle Strap Heels',
    category: 'footwear' as ItemCategory,
    brand: 'Sergio Rossi',
    color: 'Black',
    size: '38.5',
    material: 'Satin',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 780,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shoes', 'sergio-rossi', 'heels', 'satin'],
    description: 'Sergio Rossi satin ankle-strap stilettos. 105mm heel.',
    care_instructions: 'Store in dust bag. Spot clean satin carefully.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Nude Patent Leather Pumps',
    category: 'footwear' as ItemCategory,
    brand: 'Christian Louboutin',
    color: 'Nude',
    size: '38.5',
    material: 'Patent Leather',
    season: 'spring/summer',
    purchase_year: 2020,
    purchase_price: 845,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['shoes', 'louboutin', 'pumps', 'nude'],
    description: 'Christian Louboutin So Kate 120mm nude patent pumps. Current season.',
    care_instructions: 'Polish with patent leather cleaner. Protect red sole.',
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Sapphire and Diamond Earrings',
    category: 'accessories' as ItemCategory,
    brand: 'Graff',
    color: 'Blue',
    material: 'Platinum, Sapphires, Diamonds',
    season: 'all',
    purchase_year: 2015,
    purchase_price: 22000,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['jewelry', 'graff', 'sapphire', 'diamonds', 'earrings'],
    description: 'Graff drop earrings with oval sapphires and pavé diamond surrounds. Original certificate.',
    care_instructions: 'Store in original presentation box. Professional cleaning annually.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Hermès Twilly Silk Scarf Set (3)',
    category: 'accessories' as ItemCategory,
    brand: 'Hermès',
    color: 'Multicolor',
    material: 'Silk Twill',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 600,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['scarf', 'hermes', 'twilly', 'accessories'],
    description: 'Set of 3 Hermès Twilly scarves in various colorways. Boxed.',
    care_instructions: 'Hand wash cold. Press through pressing cloth.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Winter White Cashmere Shawl',
    category: 'accessories' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Winter White',
    material: 'Vicuña',
    season: 'fall/winter',
    purchase_year: 2018,
    purchase_price: 8500,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shawl', 'vicuna', 'loro-piana', 'accessories'],
    description: 'Loro Piana vicuña shawl in winter white. Museum-quality textile.',
    care_instructions: 'Professional dry clean only. Extremely rare fiber — handle with utmost care.',
  },

  // ── In Transit / Seasonal ─────────────────────────────────────────────────
  {
    client_email: 'client2@test.llv.com',
    name: 'Ivory Linen Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Max Mara',
    color: 'Ivory',
    size: '6',
    material: 'Linen',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 380,
    status: 'delivery_scheduled' as ItemStatus,
    location_status: 'in_transit' as ItemLocation,
    tags: ['linen', 'trousers', 'max-mara'],
    description: 'Max Mara linen straight-leg trousers. In transit to AZ.',
    care_instructions: 'Machine wash cold. Press with steam.',
  },
  {
    client_email: 'client2@test.llv.com',
    name: 'Navy Stripe Resort Dress',
    category: 'dresses' as ItemCategory,
    brand: 'Missoni',
    color: 'Navy Stripe',
    size: '4',
    material: 'Knit',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 1200,
    status: 'delivery_scheduled' as ItemStatus,
    location_status: 'in_transit' as ItemLocation,
    tags: ['dress', 'missoni', 'resort', 'stripe'],
    description: 'Missoni signature stripe knit dress. In transit to AZ for resort season.',
    care_instructions: 'Hand wash cold. Dry flat.',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Client 3: James Thornton — target 32 items
  // Distribution: ~15 WI stored, ~10 AZ stored/with-client, ~4 at-provider, ~3 with-client
  // ══════════════════════════════════════════════════════════════════════════

  // ── Golf Wardrobe WI ──────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'Classic Navy Performance Golf Polo',
    category: 'activewear' as ItemCategory,
    brand: 'Peter Millar',
    color: 'Navy',
    size: 'L',
    material: 'Stretch Piqué Performance Fabric',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 125,
    status: 'stored' as ItemStatus,
    location_status: 'with_client_wi' as ItemLocation,
    tags: ['golf', 'polo', 'peter-millar', 'activewear'],
    description: 'Peter Millar Crown Sport polo in navy. UV protection. Moisture-wicking.',
    care_instructions: 'Machine wash cold, tumble dry low.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'White Performance Golf Polo',
    category: 'activewear' as ItemCategory,
    brand: 'Peter Millar',
    color: 'White',
    size: 'L',
    material: 'Stretch Piqué',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 125,
    status: 'stored' as ItemStatus,
    location_status: 'with_client_wi' as ItemLocation,
    tags: ['golf', 'polo', 'peter-millar', 'activewear'],
    description: 'Peter Millar Crown Sport polo in white.',
    care_instructions: 'Machine wash cold, tumble dry low.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Stone Stretch Golf Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Bonobos',
    color: 'Stone',
    size: '34x30',
    material: 'Performance Stretch Cotton',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 180,
    status: 'stored' as ItemStatus,
    location_status: 'with_client_wi' as ItemLocation,
    tags: ['golf', 'trousers', 'bonobos'],
    description: 'Bonobos Highland performance trousers in stone. Four-way stretch. Two pairs.',
    care_instructions: 'Machine wash cold, tumble dry low.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Slate Blue Performance Wind Jacket',
    category: 'activewear' as ItemCategory,
    brand: 'Patagonia',
    color: 'Slate Blue',
    size: 'L',
    material: 'Recycled Nylon Shell',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 350,
    status: 'received' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['jacket', 'patagonia', 'golf', 'activewear'],
    description: 'Patagonia Storm10 wind shell. Packable. Waterproof zips.',
    care_instructions: 'Machine wash cold. Tumble dry low to reactivate DWR finish.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Khaki Golf Shorts (2 pairs)',
    category: 'activewear' as ItemCategory,
    brand: 'Bonobos',
    color: 'Khaki',
    size: '34',
    material: 'Performance Stretch Cotton',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 240,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_wi' as ItemLocation,
    tags: ['golf', 'shorts', 'bonobos'],
    description: 'Bonobos golf shorts in khaki. Two pairs. Currently with client in WI.',
    care_instructions: 'Machine wash cold, tumble dry low.',
  },

  // ── Golf Wardrobe AZ ──────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'Sky Blue Performance Golf Polo',
    category: 'activewear' as ItemCategory,
    brand: 'Fairway & Greene',
    color: 'Sky Blue',
    size: 'L',
    material: 'Performance Piqué',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 145,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['golf', 'polo', 'fairway-greene', 'activewear'],
    description: 'Fairway & Greene performance polo in sky blue. Scottsdale golf wardrobe.',
    care_instructions: 'Machine wash cold, tumble dry low.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Khaki Stretch Chinos',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Incotex',
    color: 'Khaki',
    size: '34x30',
    material: 'Stretch Cotton Blend',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 320,
    status: 'received' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['chinos', 'incotex', 'casual'],
    description: 'Incotex Slacks 1959 slim tapered chinos. Two pairs.',
    care_instructions: 'Machine wash cold. Press with light starch.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Desert Sand Performance Shorts',
    category: 'activewear' as ItemCategory,
    brand: 'Peter Millar',
    color: 'Desert Sand',
    size: '34',
    material: 'Performance Stretch',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 95,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['golf', 'shorts', 'peter-millar'],
    description: 'Peter Millar performance shorts in desert sand. AZ golf season staple.',
    care_instructions: 'Machine wash cold, tumble dry low.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'FootJoy Pro/SL Golf Shoes (WI)',
    category: 'footwear' as ItemCategory,
    brand: 'FootJoy',
    color: 'White/Silver',
    size: '10.5D',
    material: 'Full-Grain Leather',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 180,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['golf', 'shoes', 'footjoy'],
    description: 'FootJoy Pro/SL in white/silver. WI golf shoes.',
    care_instructions: 'Clean after each round. Store with shoe trees.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'FootJoy Traditions Golf Shoes (AZ)',
    category: 'footwear' as ItemCategory,
    brand: 'FootJoy',
    color: 'White/Tan',
    size: '10.5D',
    material: 'Full-Grain Leather',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 200,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['golf', 'shoes', 'footjoy'],
    description: 'FootJoy Traditions in white/tan. AZ golf shoes. Currently with client.',
    care_instructions: 'Clean after each round. Condition leather monthly.',
  },

  // ── Business / Formal ─────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'White French-Cuff Dress Shirt',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Eton',
    color: 'White',
    size: '16.5/34',
    material: 'Egyptian Cotton Twill',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 680,
    status: 'received' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shirt', 'eton', 'formal', 'french-cuff'],
    description: 'Eton White Signature dress shirt, French cuffs. Four identical shirts submitted together.',
    care_instructions: 'Machine wash warm, starch lightly. Professional pressing preferred.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Charcoal Herringbone Sport Coat',
    category: 'suiting' as ItemCategory,
    brand: 'Canali',
    color: 'Charcoal',
    size: '42R',
    material: 'Wool Herringbone',
    season: 'fall/winter',
    purchase_year: 2020,
    purchase_price: 1600,
    status: 'in_cleaning' as ItemStatus,
    location_status: 'at_provider_wi' as ItemLocation,
    location_label: 'Milwaukee Garment Care — Order #MKE-1188',
    tags: ['sport-coat', 'canali', 'herringbone', 'wool'],
    description: 'Canali notch-lapel sport coat in charcoal herringbone weave. Patch pockets.',
    care_instructions: 'Dry clean only. Steam to de-wrinkle. No pressing directly on wool.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Navy Worsted Wool Suit',
    category: 'suiting' as ItemCategory,
    brand: 'Hickey Freeman',
    color: 'Navy',
    size: '42R',
    material: 'Super 120s Wool',
    season: 'all',
    purchase_year: 2021,
    purchase_price: 1800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['suit', 'hickey-freeman', 'navy', 'wool'],
    description: 'Hickey Freeman Tasmanian wool two-button suit in navy. Traditional cut.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Grey Pinstripe Business Suit',
    category: 'suiting' as ItemCategory,
    brand: 'Hickey Freeman',
    color: 'Grey Pinstripe',
    size: '42R',
    material: 'Wool',
    season: 'fall/winter',
    purchase_year: 2020,
    purchase_price: 1600,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['suit', 'hickey-freeman', 'pinstripe', 'business'],
    description: 'Classic grey chalk pinstripe two-button suit.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Navy Merino Crewneck Sweater',
    category: 'knitwear' as ItemCategory,
    brand: 'Ralph Lauren Purple Label',
    color: 'Navy',
    size: 'L',
    material: 'Extra-Fine Merino',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 450,
    status: 'stored' as ItemStatus,
    location_status: 'with_client_wi' as ItemLocation,
    tags: ['knitwear', 'ralph-lauren', 'merino', 'crewneck'],
    description: 'Ralph Lauren Purple Label extra-fine merino crewneck. Classic fit.',
    care_instructions: 'Hand wash cold or dry clean. Lay flat to dry.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Camel Lambswool V-neck Sweater',
    category: 'knitwear' as ItemCategory,
    brand: 'Barbour',
    color: 'Camel',
    size: 'L',
    material: 'Lambswool',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 280,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['knitwear', 'barbour', 'lambswool', 'v-neck'],
    description: 'Barbour Horden V-neck in camel lambswool.',
    care_instructions: 'Hand wash cold or dry clean.',
  },

  // ── Outerwear ─────────────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'Waxed Canvas Field Coat',
    category: 'outerwear' as ItemCategory,
    brand: 'Barbour',
    color: 'Olive',
    size: 'L',
    material: 'Waxed Cotton',
    season: 'fall/winter',
    purchase_year: 2019,
    purchase_price: 450,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['jacket', 'barbour', 'waxed', 'outdoor'],
    description: 'Barbour Bedale waxed jacket in olive. Re-waxed 2023.',
    care_instructions: 'Do not wash. Re-wax annually. Hang dry.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Navy Cashmere Topcoat',
    category: 'outerwear' as ItemCategory,
    brand: 'Canali',
    color: 'Navy',
    size: '42R',
    material: 'Cashmere Blend',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 2200,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['topcoat', 'cashmere', 'canali', 'navy'],
    description: 'Canali single-breasted topcoat in navy cashmere blend.',
    care_instructions: 'Dry clean only.',
  },

  // ── Footwear ──────────────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'Walnut Shell Cordovan Derby Shoes',
    category: 'footwear' as ItemCategory,
    brand: 'Allen Edmonds',
    color: 'Walnut',
    size: '10.5D',
    material: 'Shell Cordovan',
    season: 'all',
    purchase_year: 2019,
    purchase_price: 650,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shoes', 'allen-edmonds', 'cordovan', 'derby'],
    description: 'Allen Edmonds McAllister in walnut shell cordovan. Full leather sole. Shoe trees included.',
    care_instructions: 'Polish with Saphir Cordovan Crème. Store with cedar shoe trees.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Black Cap-Toe Oxfords',
    category: 'footwear' as ItemCategory,
    brand: 'Allen Edmonds',
    color: 'Black',
    size: '10.5D',
    material: 'Calfskin',
    season: 'all',
    purchase_year: 2020,
    purchase_price: 420,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shoes', 'allen-edmonds', 'oxfords', 'black'],
    description: 'Allen Edmonds Park Avenue cap-toe oxfords in black.',
    care_instructions: 'Polish monthly. Store with cedar shoe trees.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Tan Suede Loafers',
    category: 'footwear' as ItemCategory,
    brand: 'Tod\'s',
    color: 'Tan',
    size: '10.5',
    material: 'Suede',
    season: 'spring/summer',
    purchase_year: 2022,
    purchase_price: 580,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['shoes', 'tods', 'loafers', 'suede'],
    description: 'Tod\'s Gommino driving loafers in tan suede.',
    care_instructions: 'Brush suede after each wear. Store in dust bag.',
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'Navy Cashmere Scarf',
    category: 'accessories' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Navy',
    material: 'Baby Cashmere',
    season: 'fall/winter',
    purchase_year: 2021,
    purchase_price: 750,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['scarf', 'cashmere', 'loro-piana'],
    description: 'Loro Piana baby cashmere scarf in navy. Double-faced. 180cm.',
    care_instructions: 'Dry clean only.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Silk Tie Collection (8 ties)',
    category: 'accessories' as ItemCategory,
    brand: 'Hermès',
    color: 'Various',
    material: 'Silk',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 2800,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['ties', 'hermes', 'silk', 'accessories'],
    description: 'Collection of 8 Hermès silk ties in various patterns. Stored in tie rolls.',
    care_instructions: 'Dry clean only. Store rolled, not folded. Avoid creasing.',
  },

  // ── Resort Scottsdale ─────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'White Linen Resort Shirt',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Peter Millar',
    color: 'White',
    size: 'L',
    material: 'Linen',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 165,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['shirt', 'linen', 'peter-millar', 'resort'],
    description: 'Peter Millar summer linen shirt. AZ resort wardrobe.',
    care_instructions: 'Machine wash cold. Iron while damp.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Navy Linen Blazer (Resort)',
    category: 'suiting' as ItemCategory,
    brand: 'Ralph Lauren',
    color: 'Navy',
    size: '42R',
    material: 'Linen',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 680,
    status: 'delivered' as ItemStatus,
    location_status: 'with_client_az' as ItemLocation,
    tags: ['blazer', 'linen', 'ralph-lauren', 'resort'],
    description: 'Ralph Lauren unlined navy linen blazer. AZ resort season staple.',
    care_instructions: 'Dry clean preferred.',
  },
  {
    client_email: 'client3@test.llv.com',
    name: 'Stone Pleated Resort Trousers',
    category: 'trousers_skirts' as ItemCategory,
    brand: 'Loro Piana',
    color: 'Stone',
    size: '34x30',
    material: 'Linen',
    season: 'spring/summer',
    purchase_year: 2023,
    purchase_price: 620,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_az' as ItemLocation,
    tags: ['trousers', 'linen', 'loro-piana', 'resort'],
    description: 'Loro Piana stone linen pleated trousers. AZ wardrobe.',
    care_instructions: 'Dry clean only.',
  },

  // ── Shirts (Business) ─────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'Blue Herringbone Business Shirts (2)',
    category: 'shirts_blouses' as ItemCategory,
    brand: 'Eton',
    color: 'Blue',
    size: '16.5/34',
    material: 'Cotton Herringbone',
    season: 'all',
    purchase_year: 2022,
    purchase_price: 480,
    status: 'stored' as ItemStatus,
    location_status: 'in_storage_wi' as ItemLocation,
    tags: ['shirts', 'eton', 'business', 'herringbone'],
    description: 'Two Eton blue herringbone dress shirts. Regular fit.',
    care_instructions: 'Machine wash warm. Press with starch.',
  },

  // ── At Provider ───────────────────────────────────────────────────────────
  {
    client_email: 'client3@test.llv.com',
    name: 'Heathered Grey Golf Vest',
    category: 'activewear' as ItemCategory,
    brand: 'Peter Millar',
    color: 'Heathered Grey',
    size: 'L',
    material: 'Merino Blend',
    season: 'fall/winter',
    purchase_year: 2022,
    purchase_price: 195,
    status: 'in_cleaning' as ItemStatus,
    location_status: 'at_provider_az' as ItemLocation,
    location_label: 'Mastel Dry Cleaning — scheduled',
    tags: ['golf', 'vest', 'peter-millar', 'merino'],
    description: 'Peter Millar heathered grey merino golf vest.',
    care_instructions: 'Dry clean preferred.',
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Item names the orders module can use for lookup
// Exported as a convenience so seed-orders can reference items by canonical name
// ─────────────────────────────────────────────────────────────────────────────

/** Margaret's items that went in the big WI→AZ seasonal rotation (order 1) */
export const MARGARET_SEASONAL_ITEMS = [
  'Midnight Navy Tuxedo Jacket',
  'Black Tuxedo Trousers',
  'Heather Grey Flannel Suit',
  'Ivory Bouclé Skirt Suit',
  'Black Cashmere Blazer',
  'Sable Brown Cashmere Overcoat',
  'Ivory Cashmere V-neck Sweater',
  'Camel Cashmere Turtleneck',
  'Navy Cashmere Cardigan',
  'Camel Wide-Leg Trousers',
  'Navy Silk Midi Skirt',
  'Black Cashmere Straight-Leg Trousers',
  'Gold Hermes Kelly 32',
  'Black Chanel Classic Flap Medium',
  'Black Patent Leather Oxfords',
  'Nude Suede Slingback Pumps',
  'Black Satin Evening Pumps',
  'Diamond Tennis Bracelet',
  'Navy Silk Twill Scarf',
  'Pearl Strand Necklace',
  "Richard's Charcoal Brioni Suit",
  "Richard's Navy Blazer",
  "Richard's Black Tuxedo Set",
  "Richard's Allen Edmonds Dress Shoes",
  "Richard's White Tuxedo Dress Shirts (3)",
]

/** Margaret's on-demand items for the in-progress cleaning order */
export const MARGARET_INPROGRESS_ITEMS = [
  'Ivory Silk Evening Gown',
]

/** Catherine's on-demand gala delivery items */
export const CATHERINE_GALA_ITEMS = [
  'Sapphire Silk Cocktail Dress',
  'Gold Drop Earrings',
  'Blush Satin Strappy Mules',
  'Cognac Python Evening Clutch',
]

/** Catherine's Valentino repair order */
export const CATHERINE_INPROGRESS_ITEMS = [
  'Blush Valentino Couture Gown',
]

/** James's seasonal rotation items */
export const JAMES_SEASONAL_ITEMS = [
  'Classic Navy Performance Golf Polo',
  'White Performance Golf Polo',
  'Stone Stretch Golf Trousers',
  'Khaki Stretch Chinos',
  'Navy Worsted Wool Suit',
  'Navy Merino Crewneck Sweater',
  'Camel Lambswool V-neck Sweater',
  'Navy Cashmere Topcoat',
  'Walnut Shell Cordovan Derby Shoes',
  'Black Cap-Toe Oxfords',
  'Navy Cashmere Scarf',
  'Silk Tie Collection (8 ties)',
  'White French-Cuff Dress Shirt',
  'Blue Herringbone Business Shirts (2)',
  'Charcoal Herringbone Sport Coat',
  'Waxed Canvas Field Coat',
  'FootJoy Pro/SL Golf Shoes (WI)',
  'Grey Pinstripe Business Suit',
  'Sky Blue Performance Golf Polo',
  'Desert Sand Performance Shorts',
]

/** James's on-demand golf resort delivery */
export const JAMES_RESORT_ITEMS = [
  'Sky Blue Performance Golf Polo',
  'Desert Sand Performance Shorts',
  'FootJoy Traditions Golf Shoes (AZ)',
  'Stone Pleated Resort Trousers',
]

/** James's upcoming seasonal rotation */
export const JAMES_UPCOMING_ITEMS = [
  'White Linen Resort Shirt',
  'Navy Linen Blazer (Resort)',
  'Stone Pleated Resort Trousers',
  'Tan Suede Loafers',
]

export async function seedItems(): Promise<SeedResult> {
  const adminClient = createAdminClient()
  let seeded = 0
  let skipped = 0
  const errors: string[] = []

  // Build client email → profile ID map
  const { data: profiles, error: profilesErr } = await adminClient
    .from('profiles')
    .select('id, email')
    .in('email', SEED_CLIENT_EMAILS)

  if (profilesErr) return { seeded: 0, skipped: 0, errors: [`Failed to load client profiles: ${profilesErr.message}`] }
  if (!profiles?.length) return { seeded: 0, skipped: 0, errors: ['No seed clients found — run seed-clients first'] }

  const clientMap: Record<string, string> = {}
  for (const p of profiles) { clientMap[p.email] = p.id }

  for (const item of SEED_ITEMS) {
    try {
      const clientId = clientMap[item.client_email]
      if (!clientId) {
        errors.push(`${item.name}: client ${item.client_email} not found`)
        continue
      }

      // Idempotency: check by name + client_id
      const { data: existing } = await adminClient
        .from('items')
        .select('id')
        .eq('client_id', clientId)
        .eq('name', item.name)
        .maybeSingle()

      if (existing) {
        skipped++
        continue
      }

      const { client_email: _clientEmail, ...itemData } = item
      const { error } = await adminClient.from('items').insert({
        ...itemData,
        client_id: clientId,
        is_seed_data: true,
      })

      if (error) throw new Error(error.message)
      seeded++
    } catch (err) {
      errors.push(`${item.name}: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  return { seeded, skipped, errors }
}
