/**
 * Generates src/lib/docs/font-data.ts: a TypeScript constant containing
 * all @font-face rules with WOFF2 fonts base64-inlined.
 *
 * Run after updating @fontsource packages:
 *   npx tsx scripts/generate-font-data.ts
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const nm = path.join(root, 'node_modules')

const fonts = [
  // Inter — body text
  { family: 'Inter', weight: 400, style: 'normal', file: '@fontsource/inter/files/inter-latin-400-normal.woff2' },
  { family: 'Inter', weight: 500, style: 'normal', file: '@fontsource/inter/files/inter-latin-500-normal.woff2' },
  { family: 'Inter', weight: 600, style: 'normal', file: '@fontsource/inter/files/inter-latin-600-normal.woff2' },
  // Cormorant Garamond — headings/masthead
  { family: 'Cormorant Garamond', weight: 300, style: 'normal', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-300-normal.woff2' },
  { family: 'Cormorant Garamond', weight: 300, style: 'italic', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-300-italic.woff2' },
  { family: 'Cormorant Garamond', weight: 400, style: 'normal', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-400-normal.woff2' },
  { family: 'Cormorant Garamond', weight: 400, style: 'italic', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-400-italic.woff2' },
  { family: 'Cormorant Garamond', weight: 500, style: 'normal', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-500-normal.woff2' },
  { family: 'Cormorant Garamond', weight: 500, style: 'italic', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-500-italic.woff2' },
  { family: 'Cormorant Garamond', weight: 600, style: 'normal', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-600-normal.woff2' },
  { family: 'Cormorant Garamond', weight: 600, style: 'italic', file: '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-600-italic.woff2' },
]

let css = ''
for (const font of fonts) {
  const fontPath = path.join(nm, font.file)
  if (!fs.existsSync(fontPath)) {
    console.error(`MISSING: ${fontPath}`)
    process.exit(1)
  }
  const b64 = fs.readFileSync(fontPath).toString('base64')
  css += `@font-face {
  font-family: '${font.family}';
  font-style: ${font.style};
  font-weight: ${font.weight};
  font-display: block;
  src: url('data:font/woff2;base64,${b64}') format('woff2');
}
`
}

const output = `// AUTO-GENERATED by scripts/generate-font-data.ts — do not edit by hand.
// Regenerate after updating @fontsource packages:  npx tsx scripts/generate-font-data.ts
export const FONT_FACE_CSS = \`${css}\`
`

const outPath = path.join(root, 'src/lib/docs/font-data.ts')
fs.writeFileSync(outPath, output, 'utf8')
const kb = Math.round(fs.statSync(outPath).size / 1024)
console.log(`Wrote ${outPath} (${kb} KB)`)
